### ISSUE TITLE
fyi - this explains how to make the winrm secure

### ISSUE THREAD

**Issue by jedi4ever** [dhoer/terraform_examples#2]
See link http://blog.superautomation.co.uk/2016/11/configuring-terraform-to-use-winrm-over.html
Trick is to execute a PS-script to generate an self-signed cert and configure that.

**Comment by dhoer** [comment]
I like what ansible did with there winrm setup.  So I might update the example with this:

```
Invoke-Expression ((New-Object System.Net.Webclient).DownloadString('https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1'))
```

What are your thoughts about this script?

**Comment by dhoer** [comment]
Merged pr
