### ISSUE TITLE
Question - Can I run example aws-winrm-instance from linux

### ISSUE THREAD

**Issue by Martin-Andersen** [dhoer/terraform_examples#4]
Sorry to spam. But I am having trouble with WinRM.

I know that WinRM are part of MS Powershell so how can I create an windows AMI on my macbook or Jenkins build server?

I need to setup a sitecore server.

**Comment by dhoer** [comment]
Take a look at https://github.com/boxcutter/windows

**Comment by dhoer** [comment]
@Martin-Andersen Nevermind, I see you want to create an ami image.  You can script the install and configuration of sitecore in `user_data` section or use a content management tool (e.g., chef or ansible) to provision the windows server. Then save the ami.  Another approach would be to use windows docker: https://developer.rackspace.com/blog/run-sitecore-in-a-docker-container-on-windows-server-2016/.
