### ISSUE TITLE
SetPassword appears to no longer work

### ISSUE THREAD

**Issue by mafrosis** [dhoer/terraform_examples#9]
Hello, thanks for sharing these terraform examples.

In my tests, the admin password is not being set, which means one cannot do any provisioning from Terraform. Does this code still work for you? Do you have any knowledge of debugging the `user_data` script from within Windows after boot?

https://github.com/dhoer/terraform_examples/blob/master/aws-winrm-instance/main.tf#L73

Thanks!

**Comment by dhoer** [comment]
Yes, that code is working for me on Amazon Windows 2012r2 AMIs.  It should also work for 2016 server as well.

**Comment by dhoer** [comment]
What happens when you run this from command shell?
```
net user user_name  new_password
```

This should change the password as well as long a you have administrator privileges.

**Comment by mafrosis** [comment]
@dhoer Thanks for sharing the `net user` command - turned out my "password didn't meet the policy".

This issue should serve to help other people with similar problems in the future!
